services:

  node1:
    build: ./broker
    container_name: node1
    ports:
      - "1883:1883"
      - "5001:5001"
      - "6000:6000"
    command: ["./app", "1", "node1", "1883", "5001", "6000", "t", "2=node2:5002:6001", "3=node3:5003:6002"]
    volumes:
      - ./broker/data/node1:/app/data

  client1:
    build: ./cliente
    container_name: client1
    depends_on:
      - node1
    command: ["./app", "1", "node1:1883"]

  sensor1:
    build: ./sensor
    container_name: sensor1
    depends_on:
      - node1
    command: ["./app", "radar", "1", "node1:1883"]

  sensor12:
    build: ./sensor
    container_name: sensor12
    depends_on:
      - node1
    command: ["./app", "sonar", "1", "node1:1883"]

  drone1:
    build: ./drone
    container_name: drone1
    depends_on:
      - node1
    command: ["./app", "1", "1=node1:1883", "2=node2:1883", "3=node3:1883"]


  node2:
    build: ./broker
    container_name: node2
    depends_on:
      - node1
    ports:
      - "1884:1883"
      - "5002:5002"
      - "6001:6001"
    command: ["./app", "2", "node2", "1883", "5002", "6001", "f", "1=node1:5001:6000", "3=node3:5003:6002"]
    volumes:
      - ./broker/data/node2:/app/data

  drone2:
    build: ./drone
    container_name: drone2
    depends_on:
      - node1
    command: ["./app", "2", "2=node2:1883", "1=node1:1883", "3=node3:1883"]

  node3:
    build: ./broker
    container_name: node3
    depends_on:
      - node1
    ports:
      - "1885:1883"
      - "5003:5003"
      - "6002:6002"
    command: ["./app", "3", "node3", "1883", "5003", "6002", "f", "1=node1:5001:6000", "2=node2:5002:6001"]
    volumes:
      - ./broker/data/node3:/app/data


  drone3:
    build: ./drone
    container_name: drone3
    depends_on:
      - node1
    command: ["./app", "3", "3=node3:1883", "2=node2:1883", "1=node1:1883"]
